/* eslint-disable jsx-a11y/anchor-is-valid */
/* eslint-disable jsx-a11y/anchor-has-content */

export default function () {
  return (
    <main className="main">
      <div className="container  width-handle">
        <div className="gap-3" />
        <div className="row">
          <div className="col-12">
            <h1 className="brand-font fs-4">Terms of Services</h1>
            <p className="text-secondary">
              101verse is a collection of digital artworks (NFTs/Ordinals)
              running on the Ethereum & Bitcoin network. This website is only an
              interface allowing participants to exchange digital collectibles.
              Users are entirely responsible for the safety and management of
              their own private Ethereum wallets and validating all transactions
              and contracts generated by this website before approval.
              Furthermore, as the 101verse smart contract runs on the Ethereum
              network, there is no ability to undo, reverse, or restore any
              transactions.
            </p>
            <p className="text-secondary">
              This website and its connected services are provided “as is” and
              “as available” without warranty of any kind. By using this website
              you are accepting sole responsibility for any and all transactions
              involving 101verse digital collectibles.{" "}
            </p>
            <h2 className="fs-5">OWNERSHIP</h2>
            <p className="text-secondary">
              i. You Own the NFT. Each 101verse is an NFT/Ordinals. When you
              purchase an NFT, you own the underlying 101verse, the Art,
              completely. Ownership of the NFT is mediated entirely by the Smart
              Contract and the Ethereum Network: at no point may we seize,
              freeze, or otherwise modify the ownership of any 101verse.
            </p>
            <p className="text-secondary">
              ii. Personal Use. Subject to your continued compliance with these
              Terms, DRI Labs grants you a worldwide, royalty-free license to
              use, copy, and display the purchased Art, along with any
              extensions that you choose to create or use, solely forthe
              following purposes: (i) for your own personal, non-commercial use;
              (ii) as part of a marketplace that permits the purchase and sale
              of your 101verse / NFT, provided that the marketplace
              cryptographically verifies each 101verse owner’s rights to display
              the Art for their 101verse to ensure that only the actual owner
              can display the Art; or (iii) as part of a third party website or
              application that permits the inclusion, involvement, or
              participation of your 101verse, provided that the
              website/application cryptographically verifies each 101verse
              owner’s rights to display the Art for their 101verse to ensure
              that only the actual owner can display the Art, and provided that
              the Art is no longer visible once the owner ofthe 101verse leaves
              the website/application.
            </p>
            <p className="text-secondary">
              iii. Commercial Use. Subject to your continued compliance with
              these Terms, DriLabs grants you an unlimited, worldwide license to
              use, copy, and display the purchased Art for the purpose of
              creating derivative works based upon the Art (“Commercial Use”).
              Examples of such Commercial Use would e.g. be the use of the Art
              to produce and sell merchandise products (T-Shirts etc.)
              displaying copies of the Art. For the sake of clarity, nothing in
              this Section will be deemed to restrict you from (i) owning or
              operating a marketplace that permits the use and sale of 101verses
              generally, provided that the marketplace cryptographically
              verifies each 101verse owner’s rights to display the Art for their
              101verse to ensure that only the actual owner can display the Art;
              (ii) owning or operating a third party website or application that
              permits the inclusion, involvement, or participation of 101verses
              generally, provided that the third party website or application
              cryptographically verifies each 101verse owner’s rights to display
              the Art for their 101verse to ensure that only the actual owner
              can display the Art, and provided that the Art is no longer
              visible once the owner of the Purchased 101verse leaves the
              website/application; or (iii) earning revenue from any of the
              foregoing.
            </p>
            <div className="gap-6" />
          </div>
        </div>
      </div>
    </main>
  );
}
